-- AlterTable
ALTER TABLE "WhatsAppInstance" ADD COLUMN     "active" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "lastResetDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "messagesSentThisMonth" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "monthlyLimit" INTEGER NOT NULL DEFAULT 1000;
